"""unique id parriba 2

Revision ID: 799019c0f69a
Revises: df9db52083fd
Create Date: 2024-09-16 15:30:56.720916

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '799019c0f69a'
down_revision = 'df9db52083fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.alter_column('unique_id',
               existing_type=sa.VARCHAR(length=512),
               type_=sa.Text(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.alter_column('unique_id',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=512),
               existing_nullable=False)

    # ### end Alembic commands ###
